print('Twinkle,' 'twinkle,' 'little star')
print('\n\tHow I wonder what you are')
print('\n\t\tUp above the world so hight,')
print('\n\t\tLike a diamond in the sky')
print('Twinkle,' 'twinkle,' 'little star')
print('\n\tHow I wonder what you are!')